name: "Build & Release"

on:
  workflow_dispatch:
    branches: main
    

jobs:
    build:
        name: Build & Release
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup-Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'
                
            - name: Clone Repository
              run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/DoodleMoviesApp.git
            
            - name: Install Dependencies
              run: cd DoodleMoviesApp && npm install

            - name: Build App file
              run: cd DoodleMoviesApp/android && ./gradlew assembleRelease

            - name: Rename APK file
              run: Rename-Item -Path "DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle-universal-v5.0.0.apk" -NewName "Doodle Movies-Universal-v5.0.0.apk"
            
            - name: Rename v7a APK file
              run: Rename-Item -Path "DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle-armeabi-v7a-v5.0.0.apk" -NewName "Doodle Movies-32bit-v5.0.0.apk"
            
            - name: Rename v8a APK file
              run: Rename-Item -Path "DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle-arm64-v8a-v5.0.0.apk" -NewName "Doodle Movies-64bit-v5.0.0.apk"
               
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Release
                path: |
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-Universal-v5.0.0.apk
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-32bit-v5.0.0.apk
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-64bit-v5.0.0.apk
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                artifacts: |
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-Universal-v5.0.0.apk
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-32bit-v5.0.0.apk
                  DoodleMoviesApp/android/app/build/outputs/apk/release/Doodle Movies-64bit-v5.0.0.apk
                tag: v5.0.0
                token: ${{secrets.SECRET_KEY}}
                prerelease: true
